# Generated by Django 3.1.7 on 2021-03-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownuser',
            name='area',
        ),
        migrations.RemoveField(
            model_name='ownuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='ownuser',
            name='is_shop_owner',
        ),
        migrations.AddField(
            model_name='ownuser',
            name='UPI_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ownuser',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ownuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
