# Generated by Django 3.1.7 on 2021-04-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provide',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
