# Generated by Django 3.1.7 on 2021-04-25 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0002_auto_20210424_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provide',
            name='who_seeker',
        ),
    ]
